grpc:
  server.:
    port: 6565

spring:
  application:
    name: grpc-client

  datasource:
    url: jdbc:postgresql://localhost:5432/mc1
    username: mc1
    password: mc1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect